export const arrows = [
  {
    id: 1,
    whiteImageUrl: '/work/1_W.png',
    greenImageUrl: '/work/1_G.png',
    workTitle: 'Have a Buddhaful day!',
    workTitle2: '해브 어 붓다풀 데이!',
    name: '강유진',
    intro: '무아 속에서, 나는 나로부터 벗어난다.',
  },
  {
    id: 2,
    whiteImageUrl: '/work/2_W.png',
    greenImageUrl: '/work/2_G.png',
    workTitle: 'HOME',
    workTitle2: 'I’m HOME',
    name: '강현정',
    intro: '가장 ‘나’다울 수 있는 곳, HOME',
  },
  {
    id: 3,
    whiteImageUrl: '/work/3_W.png',
    greenImageUrl: '/work/3_G.png',
    workTitle: 'delete my memory',
    workTitle2: '기억을 지워주세요',
    name: '권민정',
    intro: '우리는 정보 과잉의 세상에 살고 있는 것이 아니라, 필터가 고장난 세상에 살고 있습니다.',
  },
  {
    id: 4,
    whiteImageUrl: '/work/4_W.png',
    greenImageUrl: '/work/4_G.png',
    workTitle: 'Emotus',
    workTitle2: '이모터스',
    name: '김도영',
    intro: '인간을 표현한 외계sf영상물',
  },
  {
    id: 5,
    whiteImageUrl: '/work/5_W.png',
    greenImageUrl: '/work/5_G.png',
    workTitle: 'HEDN',
    workTitle2: '헤든',
    name: '김민구',
    intro:
      'HEDN은 헤드셋과 가방의 결합을 통해 조형적 실험과 사용자 경험의 확장을 동시에 제안하는 브랜드입니다.',
  },
  {
    id: 6,
    whiteImageUrl: '/work/6_W.png',
    greenImageUrl: '/work/6_G.png',
    workTitle: '겹글',
    workTitle2: 'Overletters',
    name: '김승화',
    intro: '그들은 그렇게 정해서 잘, 자주 쓰고 있다.',
  },
  {
    id: 7,
    whiteImageUrl: '/work/7_W.png',
    greenImageUrl: '/work/7_G.png',
    workTitle: 'The Grow Project',
    workTitle2: '성장 프로젝트',
    name: '김은지',
    intro: '고민은 고통이 아닌, 성장의 양분입니다.',
  },
  {
    id: 8,
    whiteImageUrl: '/work/8_W.png',
    greenImageUrl: '/work/8_G.png',
    workTitle: 'DOT',
    workTitle2: '하루 한점 DOT',
    name: '김주훈',
    intro: '하루의 한 점 기록이 모여 나를 돌본다, 하루 한 점 DOT',
  },
  {
    id: 9,
    whiteImageUrl: '/work/9_W.png',
    greenImageUrl: '/work/9_G.png',
    workTitle: 'ZZZ',
    workTitle2: 'catch some Z…',
    name: '박소연',
    intro: 'catch some Z… 우리는 당신의 여정 준비를 돕습니다.',
  },
  {
    id: 10,
    whiteImageUrl: '/work/10_W.png',
    greenImageUrl: '/work/10_G.png',
    workTitle: 'DSTL',
    workTitle2: 'Distill',
    name: '박수민',
    intro: '사라지는 감정의 구조화',
  },
  {
    id: 11,
    whiteImageUrl: '/work/11_W.png',
    greenImageUrl: '/work/11_G.png',
    workTitle: '해화 우체국',
    workTitle2: 'Haehwa Post Office',
    name: '박혜연',
    intro: '잊혀가는 편지 속 마음, 그 마음을 당신에게',
  },
  {
    id: 12,
    whiteImageUrl: '/work/12_W.png',
    greenImageUrl: '/work/12_G.png',
    workTitle: '상실 (喪失)',
    workTitle2: 'Lost',
    name: '박희건',
    intro: '잃어버린 후에야 비로소 보이는 것들을 표현한 일러스트',
  },
  {
    id: 13,
    whiteImageUrl: '/work/13_W.png',
    greenImageUrl: '/work/13_G.png',
    workTitle: 'QUACK!',
    workTitle2: '꽥!',
    name: '신유빈',
    intro: '오리와 함께하는 나이트루틴, QUACK!',
  },
  {
    id: 14,
    whiteImageUrl: '/work/14_W.png',
    greenImageUrl: '/work/14_G.png',
    workTitle: '도감',
    workTitle2: 'Dogam',
    name: '안수아',
    intro: '한국인의 멋을 이해하려면 먼저 도깨비를 알아야한다.',
  },
  {
    id: 15,
    whiteImageUrl: '/work/15_W.png',
    greenImageUrl: '/work/15_G.png',
    workTitle: '감정우체통',
    workTitle2: 'Emotional mailbox',
    name: '오서현',
    intro: '감정의 이름을 배우고 건강하게 표현할 수 있도록 돕는 동화책.',
  },
  {
    id: 16,
    whiteImageUrl: '/work/16_W.png',
    greenImageUrl: '/work/16_G.png',
    workTitle: '메디잇',
    workTitle2: 'mediit',
    name: '오지홍',
    intro: '병원의 성장을 데이터와 디자인으로 이끄는 의료 마케팅 브랜드',
  },
  {
    id: 17,
    whiteImageUrl: '/work/17_W.png',
    greenImageUrl: '/work/17_G.png',
    workTitle: '담류',
    workTitle2: '湛流',
    name: '원민정',
    intro: '고요히 흐르는 전통의 감각을, 열두 달의 시간 속에 담아낸 시각적 여정',
  },
  {
    id: 18,
    whiteImageUrl: '/work/18_W.png',
    greenImageUrl: '/work/18_G.png',
    workTitle: 'DIGITAL OFF',
    workTitle2: '디지털 오프',
    name: '이윤서',
    intro: '디지털을 끄고, 여행의 순간과 나에게 집중하다.',
  },
  {
    id: 19,
    whiteImageUrl: '/work/19_W.png',
    greenImageUrl: '/work/19_G.png',
    workTitle: 'facet',
    workTitle2: '페이셋',
    name: '이지혁',
    intro:
      'facet은 N잡러들의 복잡한 삶을 정리하고 균형을 찾을 수 있도록 돕는 올인원 라이프 매니지먼트 앱이다.',
  },
  {
    id: 20,
    whiteImageUrl: '/work/20_W.png',
    greenImageUrl: '/work/20_G.png',
    workTitle: 'Tracode',
    workTitle2: '트래코드',
    name: '전윤서',
    intro: '여행 속, 나만의 코드를 찾다.',
  },
  {
    id: 21,
    whiteImageUrl: '/work/21_W.png',
    greenImageUrl: '/work/21_G.png',
    workTitle: 'Broken Heart',
    workTitle2: 'Broken Heart: The broken window theory',
    name: '정현진',
    intro: '당신의 창문은 안전한가?',
  },
  {
    id: 22,
    whiteImageUrl: '/work/22_W.png',
    greenImageUrl: '/work/22_G.png',
    workTitle: '靑連',
    workTitle2: '청연',
    name: '정환이',
    intro: '흩어진 순간을 기록해, 개인의 청사진을 완성하는 靑連',
  },
] as const;
