export const arrows = [
  {
    id: 1,
    whiteImageUrl: '/work/arrow_W/강유진=화살표_강유진_W.png',
    greenImageUrl: '/work/arrow_G/강유진=화살표_강유진_G.png',
    workTitle: 'Have a Buddhaful day!',
    workTitle2: '해브 어 붓다풀 데이!',
    name: '강유진',
    englishName: 'Kang Yujin',
    email: 'kimnini189@gmail.com',
    instagram: 'uuuujin189 / https://www.instagram.com/uuuujin189/',
    link: '',
    intro: '무아 속에서, 나는 나로부터 벗어난다.',
    koreanExplanation:
      '이 전시는 현대인의 혼란스러운 삶 속에서 ‘나는 무엇인가’라는 질문을 불교의 무아 사상과 연결해 조형적으로 탐구합니다. 종교적 교리를 따르기보다는 근본적이고 비물질적인 태도로서의 불교철학을 오늘날의 불확실성과 맞닿게 하며, 이를 감각적이고 물질적인 디자인 언어로 치환합니다. “Have a Buddhaful Day!”라는 제목은 ‘Have a beautiful day!’라는 일상의 언어와 불교적 세계관을 교차시킨 말장난으로, 종교적 신자라기보다는 심리적 위안을 필요로 하는 현대인을 위한 제안이자 초대장입니다. 이 프로젝트는 불교의 무아사상을 종이와 잉크, 재질과 기법 같은 물질적 장치에 번역하며, 자아를 해체하는 과정을 조형적으로 재현합니다. 관람자는 그 과정 속에서 시각적 사물과 심리적 사유가 교차하는 경험을 마주하게 됩니다.',
    englishExplanation:
      'This exhibition explores the question ‘What am I?’ within the confusion of contemporary life, linking it to the Buddhist concept of non-self through a visual and spatial inquiry. Rather than following religious doctrine, it engages with Buddhist philosophy as a fundamental and immaterial attitude, bringing it into dialogue with today’s uncertainties and translating it into a sensory and material design language.The title ‘Have a Buddhaful Day!’ is a playful pun that intersects the everyday phrase ‘Have a beautiful day!’ with a Buddhist worldview. It serves less as a message for religious believers than as a proposal and an invitation for modern individuals seeking psychological comfort.This project translates the Buddhist philosophy of non-self into material devices such as paper, ink, textures, and techniques, visually re-enacting the process of dismantling the self. In doing so, it offers viewers an encounter where visual objects and psychological reflection intersect.',
  },
  {
    id: 2,
    whiteImageUrl: '/work/arrow_W/강현정=화살표_강현정_W.png',
    greenImageUrl: '/work/arrow_G/강현정=화살표_강현정_G.png',
    workTitle: 'HOME',
    workTitle2: 'I’m HOME',
    name: '강현정',
    englishName: 'Kang Hyeonjeong',
    email: 'jungl0228@naver.com',
    instagram: 'bing_bong_o3o / https://www.instagram.com/bing_bong_o3o/',
    link: '',
    intro: '가장 ‘나’다울 수 있는 곳, HOME',
    koreanExplanation:
      '집은 세상의 속도와 기준에서 잠시 벗어나 숨을 고르고, 억눌린 마음을 편히 드러낼 수 있는 감성적 공간으로서 단순한 생활의 공간을 넘어, 감정을 내려놓고 회복할 수 있는 심리적 안식처입니다. ‘HOME’은 이러한 집의 의미에서 출발한 감정 리추얼 브랜드입니다. 우리는 사회의 시선과 기준에 맞추다 보니 자신의 감정을 뒤로 미루며 살아가고, 이는 결국 ‘나다움’을 흐리게 만듭니다. ‘HOME’은 감정을 인식하고 표현하며 정화하는 과정을 통해, 흐려진 나를 다시 선명하게 되찾는 여정을 제안합니다. 각 감정 리추얼 단계에는 서로 다른 경험과 구성품을 통해 감정을 마주하고 자기회복 하도록 돕습니다.',
    englishExplanation:
      'Home is an emotional space where we can momentarily step away from the pace and standards of the world, take a breath, and gently reveal our suppressed feelings. Beyond being a simple place of living, it is a psychological sanctuary where emotions can be released and healing can take place. ‘HOME’ is an emotional ritual brand inspired by this meaning of home. As we constantly adapt to society’s gaze and expectations, we often push our own emotions aside, which eventually blurs our sense of authenticity—our true self. ‘HOME’ proposes a journey to regain that clarity by recognizing, expressing, and cleansing emotions. Each step of the emotional ritual offers different experiences and tools that help us confront our feelings and move toward self-restoration.',
  },
  {
    id: 3,
    whiteImageUrl: '/work/arrow_W/권민정=화살표_권민정_W.png',
    greenImageUrl: '/work/arrow_G/권민정=화살표_권민정_G.png',
    workTitle: 'delete my memory',
    workTitle2: '기억을 지워주세요',
    name: '권민정',
    englishName: 'Kwon Minjeong',
    intro: '우리는 정보 과잉의 세상에 살고 있는 것이 아니라, 필터가 고장난 세상에 살고 있습니다.',
    koreanExplanation:
      '“delete my memory” 캠페인은 디지털 폐기물을 정리하여 탄소 배출을 줄이고자 하는 디지털 시대의 환경 캠페인입니다. 인간의 뇌는 과부화를 막기 위해 ‘망각’이라는 필터로 불필요한 기억을 덜어내어 중요한 것을 지켜냅니다. 그러나 디지털 데이터는 스스로 사라지지 않아, 우리가 잠든 사이에도 24시간 돌아가는 데이터센터 속 약 85%는 디지털 폐기물로 남아있습니다. 이로 인한 탄소 배출은 미국 항공산업과 유사한 수준에 이릅니다. 민들레는 오래전부터 기억과 망각의 순환을 상징해왔습니다. 홀씨가 흩어져야 새로운 꽃이 피어나듯, 우리는 소중한 미래를 위해 자리를 지켜내야 합니다. Delete My Memory는 민들레의 순환에 비유해, 기억을 삭제하고 정리하는 작은 습관이 곧 미래를 지키는 약속임을 전합니다.',
    englishExplanation:
      'The Delete My Memory campaign raises awareness of the invisible threat of digital waste and emphasizes the necessity for us to become active agents of decluttering to safeguard our future. The human brain protects itself from overload by filtering out unnecessary memories through forgetting, preserving only what truly matters. Digital data, however, never disappears on its own. Even while we sleep, data centers continue to run for 24 hours, with nearly 85% of their content classified as digital waste. The resulting carbon emissions reach a level comparable to that of the U.S. aviation industry. The dandelion has long symbolized the cycle of memory and forgetting. Just as its seeds scatter to make way for the next bloom, we too must create space for a meaningful future. Delete My Memory draws on this cycle of the dandelion, showing that the simple act of deleting and organizing memories is, in fact, a promise to protect tomorrow.',
    email: 'kmg51265053@gmail.com',
    instagram: '13.03mj / https://www.instagram.com/13.03mj/',
    link: 'https://www.behance.net/9866d30f',
  },
  {
    id: 4,
    whiteImageUrl: '/work/arrow_W/김도영=화살표_김도영_W.png',
    greenImageUrl: '/work/arrow_G/김도영=화살표_김도영_G.png',
    workTitle: 'Emotus',
    workTitle2: '이모터스',
    name: '김도영',
    englishName: 'Kim Doyeong',
    intro: '인간을 표현한 외계sf영상물',
    koreanExplanation:
      '2125년, 생명 에너지 ‘포스’가 고갈되어 붕괴 직전의 지구. 인류는 마지막 희망을 걸고 우주 탐사 프로젝트를 시작합니다. 그 임무를 맡은 다섯 명의 탐사대가 바로 이모터스(Emotus)입니다. 각기 다른 국적과 배경을 가진 이들은 감정 분석, 기계 공학, 생태학, 군사 전략, 심리학 등 다양한 전문성을 지녔으며, 인류를 구원할 수 있다는 사명감과 동시에 서로 다른 욕망과 가치관을 안고 우주로 떠납니다. 그들의 첫 여정은 얼음과 물로 뒤덮인 행성 엘타르(Eltar). 이곳에서 이모터스는 감정을 결정화한 생명 에너지 ‘에모라이트’를 발견하고, 원주민들의 공동체적 삶과 철학을 목격합니다. 그러나 인류의 생존을 위해 에너지를 ‘채취’해야 하는 사명은 그들의 내적 갈등을 증폭시킵니다. 두 사람은 보존과 공존의 길을 모색하지만, 나머지 세 사람은 성급한 욕망과 개인적 야망에 휘둘려 결국 파멸을 불러옵니다. 이모터스의 이야기는 단순한 탐사의 기록이 아니라, 인간이 반복해온 선택과 실수를 응축한 비극적 서사입니다. 그들의 여정은 지구를 구하기 위한 발걸음이자, 동시에 또 다른 멸망을 향한 시작이 됩니다.',
    englishExplanation:
      'In the year 2125, Earth stands on the brink of collapse as its life force, known as the Force, is nearly depleted. Humanity entrusts its final hope to a team of five explorers — the Emotus. Coming from different nations and backgrounds, each member carries unique expertise in emotional analysis, engineering, ecology, military strategy, and psychology. Bound by the mission to save humanity, yet divided by their own desires and values, they set out into the unknown. Their first destination is Eltar, a planet of ice and water. There, the Emotus discover Emorite, a crystalline form of collective emotion, and witness the native inhabitants’ way of life built on unity and harmony. But the explorers’ duty to harvest this energy for Earth sparks tension within the team. Two seek preservation and coexistence, while the other three, driven by impatience and ambition, push toward reckless extraction—igniting a chain of choices that leads to catastrophe. The story of the Emotus is not merely one of exploration, but a tragic reflection of humanity’s recurring mistakes. Their journey, meant to save Earth, becomes a haunting reminder that the seeds of destruction often lie within.',
    email: 'doyunng020318@gmail.com',
    instagram: '',
    link: '',
  },
  {
    id: 5,
    whiteImageUrl: '/work/arrow_W/김민구=화살표_김민구_W.png',
    greenImageUrl: '/work/arrow_G/김민구=화살표_김민구_G.png',
    workTitle: 'HEDN',
    workTitle2: '헤든',
    name: '김민구',
    englishName: 'Kim Mingoo',
    intro:
      'HEDN은 헤드셋과 가방의 결합을 통해 조형적 실험과 사용자 경험의 확장을 동시에 제안하는 브랜드입니다.',
    koreanExplanation:
      'HEDN은 헤드셋과 가방을 결합한 독창적 제품 디자인을 통해 사용자가 일상 속에서 경험을 확장할 수 있는 방식을 제안합니다. 브랜드 철학을 담은 매개체로서, 패키지와 제품의 경계를 허물며 새로운 조형적 언어와 감각적 경험을 창출합니다. HEDN은 기능성과 심미성이 공존하는 동시에 개인의 라이프스타일 속에서 자연스럽게 녹아들어 디자인이 가진 본질적 가치와 가능성을 탐구합니다.',
    englishExplanation:
      'HEDN presents an innovative product design that fuses a headset with a bag, offering users an expanded experience in daily life. Beyond being a simple accessory, it serves as a medium that embodies the brand’s philosophy, dissolving the boundary between package and product to create a new visual language and sensory engagement. Balancing functionality and aesthetics, HEDN integrates seamlessly into personal lifestyles while exploring the essential value and potential of design.',
    email: 'alsrn1407@gmail.com',
    instagram: '',
    link: '',
  },
  {
    id: 6,
    whiteImageUrl: '/work/arrow_W/김승화=화살표_김승화_W.png',
    greenImageUrl: '/work/arrow_G/김승화=화살표_김승화_G.png',
    workTitle: '겹글',
    workTitle2: 'Overletters',
    name: '김승화',
    englishName: 'Kim Seunghwa',
    intro: '그들은 그렇게 정해서 잘, 자주 쓰고 있다.',
    koreanExplanation:
      '우리가 쓰는 언어는 당연한 듯 보이지만, 사실 아무 이유 없는 약속에서 시작되었습니다. ‘꽃’을 꽃이라 부르는 것도, ‘토끼’를 토끼라 부르는 것도 본질적인 이유는 없습니다. 나는 바로 이 ‘언어의 자의성’에서 출발해, 글자와 의미의 관계를 새롭게 탐구했습니다. 나는 한글의 자음과 모음을 기하학적 도형과 색으로 재구성해, 언어가 단순한 소리와 문자의 체계를 넘어 시각적 기호로도 기능할 수 있음을 실험합니다. 익숙한 글자가 낯선 형태로 변주되는 과정을 통해, 관람자는 언어가 얼마나 유연하고 창조적인 체계인지 다시 경험하게 될 것입니다.',
    englishExplanation:
      'Language may seem natural and self-evident, but in fact it begins with nothing more than arbitrary agreements. My work begins with this idea of the arbitrariness of language, exploring anew the relationship between letters and meaning.I reconstruct the consonants and vowels of Hangul into geometric shapes and colors, experimenting with how language can function not only as a system of sounds and writing but also as a visual code. Through the transformation of familiar letters into unfamiliar forms, viewers are invited to experience once again how flexible and creative a system language can be.',
    email: 'stella0433@naver.com',
    instagram: 'rtmdghk / https://www.instagram.com/rtmdghk/',
    link: 'https://www.behance.net/rtmdghk',
  },
  {
    id: 7,
    whiteImageUrl: '/work/arrow_W/김은지=화살표_김은지_W.png',
    greenImageUrl: '/work/arrow_G/김은지=화살표_김은지_G.png',
    workTitle: 'The Grow Project',
    workTitle2: '성장 프로젝트',
    name: '김은지',
    englishName: 'Kim Eunji',
    intro: '고민은 고통이 아닌, 성장의 양분입니다.',
    koreanExplanation:
      "'The Grow Project'는 당신의 고민을 위로하지 않습니다. 대신 그 과정을 통해 진정한 성장의 의미를 찾아내도록 돕는 독특한 브랜드입니다. 나이가 들수록 점점 더 입을 닫게 되는 당신, 타인에게 짐이 되고 싶지 않은 따뜻한 마음 때문에 오히려 혼자 고민을 감추는 당신에게 우리는 단순한 감정적 위로 대신, 고민을 객관적으로 분석하고 스스로 다룰 수 있는 주체적인 도구와 단단한 시스템을 제공합니다. 이 프로젝트의 핵심은 ‘고민을 양분으로 삼아 성장한다’는 철학에 있습니다. 고민을 단순히 없애야 할 고통이 아닌, 당신의 삶의 뿌리를 더욱 단단하게 만드는 중요한 자산으로 재정의하는 것입니다. 감정의 혼돈에 매몰되지 않고, 그 속에 숨은 질문과 단서를 찾아내어 무질서한 파편들을 하나의 정교한 시스템으로 재구성하는 과정을 제안합니다. 이는 시각적으로도 반영되어, 뒤엉킨 상태에서 시작해 정제되고 질서 있는 형태로 나아가는 ‘혼돈에서 질서로’의 여정을 보여줍니다. 결국 ‘The Grow Project’는 누군가 대신 짐을 짊어져 주는 것이 아니라, 당신이 스스로의 힘으로 다음 단계의 자신으로 나아갈 수 있도록 돕는 가장 강력한 도구가 되는 것을 지향합니다.",
    englishExplanation:
      'We do not exist to comfort your worries. Instead, we guide you to find growth through the very process of facing them. The Grow Project was created for those who hide their struggles to avoid burdening others.Rather than offering emotional consolation, we provide a practical tool and system that helps you objectively analyze and manage worries on your own. At our core lies the belief that worries are not pain to erase, but nutrients that strengthen the roots of life.Through finding order in chaos and reconstructing fragments into a refined system, we show how to expand without being consumed by emotion. This philosophy is also visualized in our design, moving from complexity to clarity — a journey from chaos to order.Ultimately, The Grow Project does not carry your burdens for you, but aspires to be the strongest tool that empowers you to grow on your own.',
    email: 'gee5288@hanmail.net',
    instagram: 'adorab1e.j / https://www.instagram.com/adorab1e.j/',
    link: 'https://www.behance.net/eunji__',
  },
  {
    id: 8,
    whiteImageUrl: '/work/arrow_W/김주훈=화살표_김주훈_W.png',
    greenImageUrl: '/work/arrow_G/김주훈=화살표_김주훈_G.png',
    workTitle: 'DOT',
    workTitle2: '하루 한점 DOT',
    name: '김주훈',
    englishName: 'Kim Joohoon',
    intro: '하루의 한 점 기록이 모여 나를 돌본다, 하루 한 점 DOT',
    koreanExplanation:
      '「DOT」은 하루의 작은 실천을 ‘한 점’으로 기록하며 자기 돌봄을 발견하는 브랜드입니다. 작은 점은 단순한 메모가 아니라, 오늘 내가 나를 챙겼다는 증거이자 삶의 흐름을 보여주는 흔적입니다. 하루하루 남긴 점들이 모이면 나만의 패턴과 리듬이 드러나고, 이는 곧 나를 이해하고 지탱하는 힘이 됩니다. DOT은 이러한 과정을 통해 자기 돌봄이 거창한 것이 아니라 일상 속에서 충분히 가능하다는 메시지를 전합니다. DOT은 앱, 아카이브북, 전시라는 다양한 매체로 확장되어, 기록을 단순히 남기는 데서 그치지 않고 소소한 자기 돌봄의 순간을 시각화하며, 꾸준히 자신을 돌볼 수 있도록 유도하는 트리거가 됩니다. 결국 DOT은 작은 기록이 모여 나를 돌보는 문화를 만들어가는 브랜드입니다.',
    englishExplanation:
      '「DOT」 is a brand that discovers self-care through recording a single “dot” of small daily practices.Each dot is more than just a note—it is proof that I took care of myself today, and a trace that reveals the flow of life. As these dots accumulate day by day, they unfold into my own unique patterns and rhythms, becoming a source of understanding and strength. Through this process, DOT conveys the message that self-care does not have to be grand, but is fully possible within everyday moments.Expanding into an app, an archive book, and exhibitions, DOT goes beyond simple documentation. It visualizes small moments of self-care and acts as a trigger that encourages continuous care for oneself.Ultimately, DOT is a brand that transforms small records into a culture of self-care.',
    email: 'hayul14@naver.com',
    instagram: '',
    link: '',
  },
  {
    id: 9,
    whiteImageUrl: '/work/arrow_W/박소연=화살표_박소연_W.png',
    greenImageUrl: '/work/arrow_G/박소연=화살표_박소연_G.png',
    workTitle: 'ZZZ',
    workTitle2: 'catch some Z…',
    name: '박소연',
    englishName: 'Park Soyeon',
    intro: 'catch some Z… 우리는 당신의 여정 준비를 돕습니다.',
    koreanExplanation:
      '“잠은 보약이다”라는 철학에서 출발한 ‘ZZZ’는 현대인의 부족한 수면이 건강과 일상에 미치는 영향을 깊이 인식하고, 누구나 온전한 휴식을 누릴 권리가 있다는 믿음으로 시작된 브랜드입니다. 단순한 제품이 아니라, 수면이라는 가장 본질적인 회복의 과정을 지켜내기 위한 대안이자 경험을 제안합니다. ‘ZZZ’는 사용자의 고유한 취향과 감각을 존중하며, 오롯이 나만을 위한 수면 공간을 완성하는 것을 목표로 합니다. 하루의 끝에서 ‘ZZZ’는 단순한 휴식이 아닌 깊은 치유와 회복의 시간을 선사합니다. 나만의 공간에서 경험하는 평온한 잠을 통해 삶의 균형과 활력을 되찾고, 진정한 수면의 가치를 다시 발견하도록 돕습니다.',
    englishExplanation:
      'Born from the philosophy that “sleep is the best medicine,” ‘ZZZ’ recognizes the profound impact of poor sleep on modern life and health, and begins with the belief that everyone deserves true rest. More than just products, we offer an experience that protects and enriches the most essential process of recovery—sleep itself. ‘ZZZ’ values each individual’s unique taste and sensibility, with the aim of creating a sleep space that belongs entirely to you. At the end of the day, ‘ZZZ’ delivers not just rest, but moments of deep healing and renewal. Through peaceful sleep in your own space, we help you regain balance, restore vitality, and rediscover the true value of rest.',
    email: 'thdus6288@naver.com',
    instagram: '',
    link: '',
  },
  {
    id: 10,
    whiteImageUrl: '/work/arrow_W/박수민=화살표_박수민_W.png',
    greenImageUrl: '/work/arrow_G/박수민=화살표_박수민_G.png',
    workTitle: 'DSTL',
    workTitle2: 'Distill',
    name: '박수민',
    englishName: 'Park Sumin',
    intro: '사라지는 감정의 구조화',
    koreanExplanation:
      '이 프로젝트는 ‘지금 이 순간은 다시 돌아오지 않는다’는 삶의 본질적 한계에서 출발하였습니다. 우리는 순간을 붙잡기 위해 사진을 찍고 글을 남기지만, 그 속의 감정과 밀도는 쉽게 사라져 버립니다. 저에게 이러한 순간을 더 깊고 선명하게 인식하게 해준 매개는 술과 그 자리에 머무른 대화였습니다. 술은 평소에 하지 못했던 감정을 솔직하게 나누게 만들었고, 그 과정 속에서 순간을 의미 있게 남기는 일의 가치를 깨닫게 하였습니다. 본 프로젝트는 그렇게 흘러가는 감정과 기억을 붙잡고, 그 잔향을 시각적·언어적·구조적으로 기록하여 공유하는 시도입니다. 특히 진(Gin)은 무색의 베이스 스피릿에 다양한 보태니컬 향을 더해 완성되는 술로, 투명하지만 각기 다른 정체성을 지니고 있습니다. 이는 휘발되고 침전되는 감정의 구조와 닮아 있으며, 감정이 시간과 관계를 거치며 걸러지고 남는 과정을 상징합니다. 따라서 이 전시는 사라지는 감정을 증류하듯 정제하고, 그 잔향을 하나의 구조물로 제시함으로써 순간을 어떻게 간직하고 나눌 수 있는가에 대한 탐구를 담고 있습니다.',
    englishExplanation:
      'This project begins with the fundamental limitation of life: “the present moment never returns.” We try to capture fleeting moments through photographs and writing, yet the density of emotions within them often fades away. For me, the medium that made these moments deeper and more vivid was alcohol and the conversations shared around it. Alcohol brought out emotions that are usually left unspoken, and through those exchanges I came to realize the true value of preserving a moment meaningfully. This project seeks to hold onto such emotions and memories, to distill their lingering traces, and to share them through visual, linguistic, and structural expression. Gin, in particular, becomes the central metaphor. Gin is a colorless base spirit infused with diverse botanicals, remaining transparent yet carrying distinct identities. This duality mirrors the nature of emotions—volatile yet sedimented, fleeting yet leaving behind a structure. Just as gin is distilled into clarity while preserving its layered aromas, emotions are filtered and refined over time and through relationships, leaving behind a deeper essence. Thus, this exhibition is an exploration of how vanishing emotions can be distilled, how their traces can be visualized, and how those remnants can be shared as enduring structures of memory.',
    email: 'qkrtnals0118@naver.com',
    instagram: 'sxumins / https://www.instagram.com/sxumins/',
    link: 'https://www.behance.net/d69b6d23/projects',
  },
  {
    id: 11,
    whiteImageUrl: '/work/arrow_W/박해연=화살표_박해연_W.png',
    greenImageUrl: '/work/arrow_G/박해연=화살표_박해연_G.png',
    workTitle: '해화 우체국',
    workTitle2: 'Haehwa Post Office',
    name: '박해연',
    englishName: 'Park Haeyeon',
    intro: '잊혀가는 편지 속 마음, 그 마음을 당신에게',
    koreanExplanation:
      "손으로 직접 편지를 쓰고 기다리고 읽는 과정은 단순한 소통 그 이상의 의미를 지닙니다. 편지 작성은 스스로의 감정을 언어로 구조화하며 자기 성찰을 경험하게 하고, 손글씨의 형태와 종이의 질감 같은 물리적 매개체는 디지털 메시지보다 훨씬 강한 정서적 흔적을 남기게 됩니다. 그러나 디지털을 통한 소통은 즉각성과 효율성을 앞세우는 대신 감정과 관계의 질적 깊이를 희생시키고 있습니다. 오늘날 사람들은 한 글자 한 글자 마음을 담아 써 내려가던 편지의 따뜻함과 두근거림은 점차 잊어 버리고, 빠르게 읽고 넘겨버리는 디지털 메시지로 소통 방식이 대체되고 있는 상황입니다. 이러한 현실을 ‘해화 우체국'이라는 상상의 공간을 통해 조명해 보고자 합니다. 바닷속 우체부들이 유리병 속에 편지를 담아 배달하는 모습을 통해 사람들이 편지에 대해 다시금 생각해 보게 되기를 기대합니다.",
    englishExplanation:
      'The process of writing, waiting, and reading letters by hand is more than just communication. Writing letters allows you to experience self-reflection by structuring your emotions into language, and physical media, such as the shape of your handwriting and the texture of your paper, leave a much stronger emotional mark than digital messages. However, instead of prioritizing immediacy and efficiency, digital communication is sacrificing the qualitative depth of emotions and relationships. Today, people are gradually forgetting the warmth and palpitations of letters written word by word and heart, and communication methods are being replaced by digital messages that quickly read and pass on. I would like to illuminate this reality through an imaginary space called the Haehwa Post Office. I hope that people will think twice about letters by seeing the postmen in the sea deliver them in glass bottles.',
    email: 'godus3239@gmail.com',
    instagram: '',
    link: '',
  },
  {
    id: 12,
    whiteImageUrl: '/work/arrow_W/박희건=화살표_박희건_W.png',
    greenImageUrl: '/work/arrow_G/박희건=화살표_박희건_G.png',
    workTitle: '상실 (喪失)',
    workTitle2: 'Lost',
    name: '박희건',
    englishName: 'Park Huigeon',
    intro: '잃어버린 후에야 비로소 보이는 것들을 표현한 일러스트',
    koreanExplanation:
      '이 작업은 상실의 감정을 중심으로 한 일련의 일러스트레이션을 통해, 잃어버린 후에야 비로소 깨닫게 되는 것들을 표현합니다. 잃음과 그에 따른 결핍이 가져오는 감정적 여운을 깊이 탐구하며, 시각적으로는 흑백과 미니멀한 구성을 활용하여 상실의 공허함과 동시에 내면의 복잡함을 드러냅니다. 작품은 보는 이로 하여금 상실의 순간과 그 이후의 감정 변화를 함께 느끼고 성찰하게 합니다.',
    englishExplanation:
      'This work is a series of illustrations centered on the emotion of loss, expressing the realizations that come only after something is lost. It deeply explores the emotional aftermath and void that loss and absence bring, using black-and-white and minimal compositions to visually convey both emptiness and inner complexity. The pieces invite viewers to experience and reflect on the moment of loss and the subsequent emotional shifts.',
    email: '',
    instagram: '',
    link: '',
  },
  {
    id: 13,
    whiteImageUrl: '/work/arrow_W/신유빈=화살표_신유빈_W.png',
    greenImageUrl: '/work/arrow_G/신유빈=화살표_신유빈_G.png',
    workTitle: 'QUACK!',
    workTitle2: '꽥!',
    name: '신유빈',
    englishName: 'Shin Yubeen',
    intro: '오리와 함께하는 나이트루틴, QUACK!',
    koreanExplanation:
      '현대인에게 밤은 단순히 하루를 마무리하는 시간이 아니라, 스스로를 회복하고 내일을 준비하는 중요한 전환의 순간입니다. 그러나 ‘나이트 루틴’이라는 개념은 점차 스킨케어와 외적 관리에만 집중되며, 정작 정신적 안정이나 마음챙김의 본래 의미는 흐려지고 있습니다. 긴 시간과 과도한 소비가 요구되는 루틴은 바쁜 일상 속에서 오히려 부담이 되기도 합니다. QUACK!은 목욕과 다이어리, 작은 습관들을 통해 몸과 마음을 함께 회복하는 나이트 루틴 브랜드를 제안합니다. 브랜드의 중심에는 오리 캐릭터 ‘퐁’이 있으며, 이는 단순한 장식 요소가 아니라 친근한 매개체로서 루틴을 즐겁고 편안하게 경험할 수 있도록 돕습니다. 다양한 제품군에 캐릭터와 일관된 시각 체계를 적용하여, 사용자가 하나의 루틴 속에서 연결성과 안정감을 느끼도록 설계했습니다.',
    englishExplanation:
      "For modern people, night is not merely the time to end the day, but a crucial moment of transition to recover oneself and prepare for tomorrow. However, the concept of a ‘night routine’ has gradually become focused solely on skincare and external grooming, blurring the original meaning of mental stability and mindfulness. Routines demanding excessive time and consumption can become a burden in busy daily lives. QUACK! proposes a night routine brand that restores both body and mind through bathing, journaling, and small habits. At the brand's heart is the duck character ‘Pong,’ not merely a decorative element but a friendly medium that helps make the routine enjoyable and comfortable. A consistent visual system featuring the character is applied across diverse product lines, designed to give users a sense of connection and stability within a single routine.",
    email: 'ssyb1109@naver.com',
    instagram: '',
    link: '',
  },
  {
    id: 14,
    whiteImageUrl: '/work/arrow_W/안수아=화살표_안수아_W.png',
    greenImageUrl: '/work/arrow_G/안수아=화살표_안수아_G.png',
    workTitle: '도감',
    workTitle2: 'Dogam',
    name: '안수아',
    englishName: 'An Suah',
    intro: '한국인의 멋을 이해하려면 먼저 도깨비를 알아야한다.',
    koreanExplanation:
      '한국인들은 어린 시절부터 도깨비 이야기를 듣고 자랐으며 여전히 우리 문화에서 설화, 민담, 동화 등 다양한 형태로 전해지고 있습니다. 이처럼 도깨비는 한국인의 정신과 문화를 형성하는 중요한 상징적 존재 중 하나로, 한국 설화에서 사회적 맥락에 따라 다양한 의미를 지니며 단순한 미신적 존재가 아닌 사회문화적으로 재구성되어온 존재임을 보여줍니다. 이처럼 도깨비는 복합적이고 다층적인 존재로 분석되지만 이를 시각적으로 정리하거나 매체화한 사례는 미비하며, 디자인 기반의 콘텐츠로 확장되기보다는 문헌 중심에 머물러 있어 일반 대중은 도깨비의 복합적 상징을 파악하기 어렵습니다. 더불어 현대의 다양한 매체에서 도깨비가 친숙하게 소비되는 과정에서, 그 전통성과 고유한 문화적 맥락은 외형적 이미지에 가려지곤 했습니다. 이에 본 프로젝트는 텍스트 중심으로만 전승되던 도깨비의 민속학적·전통적 정보를 시각 콘텐츠로 재구성함으로써 보다 객관적이고 접근성 높은 자료로 전환하고자 합니다. 아가 이를 바탕으로 도깨비의 서사를 현대적 관점에서 새롭게 조명하고, 창작 과정 속에서도 그 깊이와 맥락을 반영할 수 있는 가능성을 제시하고자 합니다. 이러한 시도는 도깨비가 현대인들에게 새로운 창작의 원천으로 확장시키는 계기가 되길 기대합니다.',
    englishExplanation:
      'Koreans have grown up hearing stories about Dokkaebi (goblins) since childhood, and they continue to be passed down in our culture in various forms, including folktales, tales, and fairy tales. As such, Dokkaebi is a crucial symbolic figure that shapes the Korean spirit and culture. In Korean folktales, Dokkaebi holds diverse meanings depending on the social context, demonstrating that it is not simply a superstitious entity but has been reconstructed through socio-cultural lens. Though Dokkaebi is considered a complex and multi-layered entity, there are few examples of visual representations or media adaptations of Dokkaebi. These representations remain largely literary rather than expanded into design-based content, making it difficult for the general public to grasp the complex symbolism of Dokkaebi. Furthermore, as Dokkaebi becomes familiar and accessible across various modern media, its traditional character and unique cultural context are often obscured by superficial imagery. This project aims to transform the folkloric and traditional information about Dokkaebi, previously transmitted solely through text, into visual content, transforming it into a more objective and accessible resource. Based on this, we aim to shed new light on the Dokkaebi narrative from a contemporary perspective and suggest possibilities for reflecting its depth and context within the creative process. We hope that these attempts will serve as an opportunity to expand the goblin as a new source of creativity for modern people.',
    email: 'suah4419@gmail.com',
    instagram: 'ss_u___a / https://www.instagram.com/ss_u___a/',
    link: 'https://www.behance.net/e965f8b7',
  },
  {
    id: 15,
    whiteImageUrl: '/work/arrow_W/오서현=화살표_오서현_W.png',
    greenImageUrl: '/work/arrow_G/오서현=화살표_오서현_G.png',
    workTitle: '감정우체통',
    workTitle2: 'Emotional mailbox',
    name: '오서현',
    englishName: 'Oh Seohyeon',
    intro: '감정의 이름을 배우고 건강하게 표현할 수 있도록 돕는 동화책.',
    koreanExplanation:
      '감정우체통은 어린이가 자신의 마음에 이름을 붙이고, 그것을 안전하게 꺼내어 들여다보는 법을 배우도록 돕는 동화책입니다. 우리 모두는 기쁨·분노·아쉬움·질투 같은 감정을 매일 경험하지만, 그것을 말로 옮기고 다루는 능력은 저절로 익혀지지 않습니다. 이 작품은 ‘감정이 우체통으로 전해온다’라는 친숙한 장치를 통해 상징적 상황을 만들고, 주인공 아토의 반응을 따라가며 감정의 등장·증폭·수용·해소 과정을 보여줍니다. 동화책은 어린 시절의 기억이나 상상만을 담고 있는 것이 아닙니다. 우리는 그 안에서 감정과 생각을 천천히 들여다보고, 스스로를 이해하는 시간을 갖습니다. 이야기를 따라가며 작은 사건과 선택들을 마주하고, 그 속에서 보이는 인물들의 태도나 마음을 관찰합니다. 그렇게 동화책은 단순한 읽을거리가 아니라, 일상 속에서 놓치기 쉬운 감정을 재확인하고, 자신과 세계를 조용히 돌아보게 하는 시각적인 도구가 됩니다. 동화는 아동뿐만 아니라 감정적으로 성숙하지 않은 어른들을 위한 것이기도 합니다. 저는 이들을 위해 기획을 시작하였고, 그들이 활동을 통해, 자신의 감정을 마주 볼 수 있게 되어 성장을 도울 수 있는 기회가 되길 바랍니다.',
    englishExplanation: `"Emotional Mailbox" is a children's book that helps children learn to name their feelings and safely take them out and examine them. We all experience emotions like joy, anger, regret, and jealousy every day, but the ability to put them into words and manage them doesn't come naturally. This work uses the familiar device of "emotions being delivered through a mailbox" to create a symbolic situation and, following the protagonist Ato's reactions, shows the process of emotions emerging, amplifying, accepting, and resolving. Children's books don't just contain childhood memories or imaginations. Within them, we slowly introspect our emotions and thoughts, and take time to understand ourselves. As we follow the story, we encounter small events and choices, and observe the characters' attitudes and emotions. In this way, children's books are not simply reading materials; they become visual tools that reaffirm emotions often overlooked in everyday life and allow us to quietly reflect on ourselves and the world. Fairy tales are not only for children, but also for emotionally immature adults. I began planning this project for them, hoping that through activities, they will be able to face their emotions and grow.`,
    email: '5dews@naver.com',
    instagram: '',
    link: '',
  },
  {
    id: 16,
    whiteImageUrl: '/work/arrow_W/오지홍=화살표_오지홍_W.png',
    greenImageUrl: '/work/arrow_G/오지홍=화살표_오지홍_G.png',
    workTitle: '메디잇',
    workTitle2: 'mediit',
    name: '오지홍',
    englishName: 'Oh Jihong',
    intro: '병원의 성장을 데이터와 디자인으로 이끄는 의료 마케팅 브랜드',
    koreanExplanation:
      '메디잇은 병원의 문제를 데이터와 창의적인 디자인으로 해결하여, 의료 혁신과 환자 경험 향상을 동시에 실현하는 병원 전문 마케팅 브랜드입니다. 우리는 단순히 눈에 보이는 광고 제작에 머무르지 않습니다. 병원이 진정으로 성장할 수 있도록 통합적이고 지속 가능한 전략을 설계합니다. 의료 분야는 광고 심의 규정, 개인정보 보호, 서비스 구조 등 다른 산업과는 전혀 다른 특수성을 지니고 있습니다. 메디잇은 이러한 맥락을 깊이 이해하며, 맞춤형 솔루션을 제공합니다. 특히 수도권 외 지방 병원들은 인력과 자원의 제약으로 차별화된 브랜딩이나 환자 경험 개선이 쉽지 않습니다. 메디잇은 이들에게 실질적인 대안을 제시하고 지역 경쟁력 강화를 돕습니다. 우리는 데이터를 기반으로 문제를 정확히 진단하고, 창의적인 디자인을 통해 환자와 지역 사회에 효과적으로 전달합니다. 메디잇은 단순한 마케팅 대행사가 아닌, 병원의 성장을 함께 설계하는 진정한 파트너입니다.',
    englishExplanation:
      'Mediit is a specialized marketing brand for hospitals, solving medical challenges through data-driven strategies and creative design, realizing both healthcare innovation and enhanced patient experience. We do not stop at creating visible advertisements. Instead, we design integrated and sustainable strategies that enable hospitals to achieve genuine growth. Healthcare has unique characteristics unlike other industries, such as strict advertising regulations, patient privacy protection, and complex service structures. Mediit understands these contexts deeply and provides tailored solutions. In particular, hospitals outside metropolitan areas often lack professional staff and resources, making differentiated branding and patient experience improvements difficult. Mediit offers practical alternatives to these hospitals, helping them strengthen their competitiveness within their local communities. We diagnose hospital challenges with data-based precision and deliver solutions effectively to patients and communities through creative design. Mediit is not just a marketing agency, but a true partner in shaping the sustainable growth of hospitals.',
    email: 'tronjihong@naver.com',
    instagram: '0hjihong / https://www.instagram.com/0hjihong/',
    link: '',
  },
  {
    id: 17,
    whiteImageUrl: '/work/arrow_W/원민정=화살표_원민정_W.png',
    greenImageUrl: '/work/arrow_G/원민정=화살표_원민정_G.png',
    workTitle: '담류',
    workTitle2: '湛流',
    name: '원민정',
    englishName: 'Won Minjung',
    intro: '고요히 흐르는 전통의 감각을, 열두 달의 시간 속에 담아낸 시각적 여정',
    koreanExplanation:
      '우리는 전통을 자주 ‘과거에 속한 것’으로 여깁니다. 정제되고 장엄하지만 일상과는 먼, 박물관 속 이미지로 기억되곤 합니다. 그러나 전통은 흐르고, 스며들며, 시대의 감각에 따라 다시 살아날 수 있는 존재입니다. ‘담류(湛流)’는 그런 흐름의 가능성에 대한 응답이다. ‘고요히 흐르는 물’이라는 이름처럼, 전통이 조용하지만 꾸준하게 오늘의 시간 속으로 스며들 수 있음을 상상하며 시작된 작업입니다. 하나의 시간 단위이자 생활의 일부인 달력은, 과거와 현재, 계절과 감각을 잇는 도구가 되어줍니다. 이 프로젝트는 12달의 순환 구조를 빌려 한국 전통 식물문을 현대의 시각 언어로 재해석하며, 전통이 머무는 방식과 흐르는 방향에 대해 조용한 질문을 던집니다. 전통은 박제된 유산이 아니라, 오늘의 감각 속에 살아 숨 쉴 수 있다는 확신. 이 믿음이 이 작업의 출발점이자 도착점입니다.',
    englishExplanation:
      'We often perceive tradition as something that belongs to the past—elegant and dignified, yet distant from our everyday lives, preserved only in museums. But tradition does not remain still; it flows, seeps in, and comes alive again through the lens of contemporary sensibilities. Damryu (湛流), meaning “a quiet, flowing stream,” responds to this possibility of movement. Inspired by the idea that tradition can quietly return to the rhythms of the present, this project reimagines Korean traditional floral patterns through the familiar structure of a twelve-month calendar. As a medium tied to both time and daily routine, the calendar becomes a bridge—linking past and present, seasons and senses. Rather than restoring the past, Damryu quietly asks how tradition might stay and flow again—how it might live within us once more. The belief that tradition is not a relic but a living presence in today’s design language is both the beginning and the destination of this work.',
    email: 'jung2yaa@naver.com',
    instagram: 'wonmj_1027 / https://www.instagram.com/wonmj_1027/',
    link: 'https://www.behance.net/minjungwon1',
  },
  {
    id: 18,
    whiteImageUrl: '/work/arrow_W/이윤서=화살표_이윤서_W.png',
    greenImageUrl: '/work/arrow_G/이윤서=화살표_이윤서_G.png',
    workTitle: 'DIGITAL OFF',
    workTitle2: '디지털 오프',
    name: '이윤서',
    englishName: 'Lee Yunseo',
    intro: '디지털을 끄고, 여행의 순간과 나에게 집중하다.',
    koreanExplanation:
      'Digital OFF는 디지털이 일상이 된 시대에 여행의 본질을 되묻는 프로젝트입니다. 우리는 편리한 기기에 의존해 길을 찾고 기록을 남기지만, 그 과정에서 스스로 경험하고 기억할 기회를 잃어가고 있습니다. 이 브랜드는 바로 그 지점에서 출발합니다. 디지털을 끔으로써 눈에 들어오는 것들, 주머니에 넣은 나뭇잎이나 손에 쥔 티켓처럼 사소하지만 선명한 흔적들이 아날로그적 여행의 가치를 말해줍니다. Digital OFF는 이러한 경험을 가능하게 하기 위해 기록과 수집, 휴식을 지원하는 여행 키트를 제안합니다. 그 안에는 글을 쓰고 남기는 행위가 중요한 축으로 자리하며, 손으로 남긴 기록이야말로 기억을 오래 붙잡는 방식임을 강조합니다. 또한 브랜드는 스탬프 특유의 번짐과 불균일한 자국을 활용해, 디지털 화면의 매끈함과 대비되는 아날로그적 감각을 드러냅니다. 이러한 질감은 여행에서 마주칠 수 있는 야생화, 나뭇잎, 조개껍데기, 돌멩이 같은 자연물을 브랜드의 비주얼로 표현하는 데 적용되며, 이를 통해 패키지와 엽서, 기록 도구 등 브랜드의 제품 전반에 ‘수집과 기록’의 감각을 담아냈습니다. 따라서 DIGITAL OFF는 여행의 경험을 통해 멀어져가던 아날로그의 가치를 전달하고, 삶의 균형을 제공하고자 합니다.',
    englishExplanation:
      'Digital OFF is a project that reconsiders the essence of travel in an age where digital has become everyday life. We rely on convenient devices to navigate and record, but in the process we lose the chance to truly experience and remember for ourselves. This brand begins from that very point. By turning digital off, we start to notice the small yet vivid traces—a leaf slipped into a pocket or a ticket held in hand—that reveal the value of analog travel. Digital OFF proposes a travel kit designed to support acts of recording, collecting, and resting. At its core lies the importance of writing and leaving marks by hand, emphasizing that such traces are what allow memories to endure. The brand also employs the smudged and irregular textures of stamps, highlighting an analog sensibility in contrast to the smoothness of digital screens. These textures are applied to visual motifs drawn from natural objects encountered on a journey—wildflowers, leaves, shells, and stones—infusing products such as packages, postcards, and recording tools with the spirit of collecting and remembering. In this way, Digital OFF seeks to restore the fading value of analog through the travel experience and to offer balance in life.',
    email: 'anies112@naver.com',
    instagram: 'y.unseo_2 / https://www.instagram.com/y.unseo_2/',
    link: '',
  },
  {
    id: 19,
    whiteImageUrl: '/work/arrow_W/이지혁=화살표_이지혁_W.png',
    greenImageUrl: '/work/arrow_G/이지혁=화살표_이지혁_G.png',
    workTitle: 'facet',
    workTitle2: '페이셋',
    name: '이지혁',
    englishName: 'Lee Jihyeok',
    intro:
      'facet은 N잡러들의 복잡한 삶을 정리하고 균형을 찾을 수 있도록 돕는 올인원 라이프 매니지먼트 앱이다.',
    koreanExplanation:
      'facet은 다중 직업을 가진 N잡러들이 자신의 삶을 체계적으로 정리하고 균형을 유지할 수 있도록 돕는 라이프 매니지먼트 앱입니다. 일정, 수입, 포트폴리오, 번아웃 관리, 커뮤니티라는 다섯 가지 핵심 기능을 통해 복잡하게 흩어진 일상과 업무를 하나의 흐름으로 연결합니다. 사용자는 이 앱을 통해 직업별로 분산된 스케줄과 데이터를 한눈에 파악하고, 자신이 걸어온 과정을 축적된 기록으로 확인하며, 동시에 자기 관리와 사회적 연결을 경험할 수 있습니다. facet은 단순한 일정 관리 도구를 넘어, N잡러의 삶 전체를 조망하고 지속 가능한 성장을 도와주는 동반자를 지향합니다.',
    englishExplanation:
      'facet is a life management app designed for multi-job professionals, often called “N-jobs,” who seek to organize their complex routines and maintain balance. Through its five core features—schedule management, income tracking, portfolio building, burnout management, and community—facet connects scattered aspects of daily life into a coherent flow. Users can easily oversee their diverse schedules and data, reflect on their accumulated progress, and benefit from both self-regulation and social support. More than just a scheduling tool, facet aspires to be a companion that helps N-jobs gain clarity, sustain growth, and embrace a more meaningful way of working and living.',
    email: 'minamone19@gmail.com',
    instagram: '',
    link: '',
  },
  {
    id: 20,
    whiteImageUrl: '/work/arrow_W/전윤서=화살표_전윤서_W.png',
    greenImageUrl: '/work/arrow_G/전윤서=화살표_전윤서_G.png',
    workTitle: 'Tracode',
    workTitle2: '트래코드',
    name: '전윤서',
    englishName: 'Jeon Yoonseo',
    intro: '여행 속, 나만의 코드를 찾다.',
    koreanExplanation:
      '여행은 단순한 이동이나 휴식이 아니라 개인의 성향이 드러나는 특별한 과정입니다. 누군가는 철저한 계획 속에서 안정을 찾고, 또 다른 이는 즉흥적인 흐름을 즐기며 자유로움을 느낍니다. 어떤 이는 미지의 장소를 탐험하며 모험을 추구하고, 또 다른 이는 여유와 치유를 가장 큰 가치로 삼습니다. 소비 습관과 동행에 대한 태도 역시 사람마다 달라, 같은 여행에서도 전혀 다른 경험이 만들어집니다. 그러나 지금까지의 여행 콘텐츠는 목적지와 정보 중심에 치우쳐, 정작 여행자의 성향을 이해하고 조율할 수 있는 장치는 부족했습니다. 이에 본 프로젝트 Tracode는 여행자의 성향을 네 가지 축으로 나누어 테스트화하고, 이를 통해 각자가 가진 고유한 여행 방식을 코드로 발견할 수 있도록 합니다. TraCode는 나 자신의 성향을 드러내는 동시에, 타인과의 차이를 이해하고 새로운 관계와 여정을 모색할 수 있는 경험을 제안합니다.',
    englishExplanation:
      'Travel is not merely about moving from one place to another, but a unique process in which one’s personality is revealed. Some find comfort in meticulous planning, while others embrace the freedom of spontaneity. Some pursue adventure by exploring the unknown, while others value relaxation and healing above all. Spending habits and attitudes toward companions also vary, shaping completely different experiences within the same journey. Yet, most travel content has focused on destinations and information, often overlooking tools that help us understand and adjust to these personal differences. Tracode addresses this by framing travel tendencies into four axes and transforming them into a test, allowing each individual to discover their own unique travel code. More than a result sheet, TraCode becomes a way to understand yourself, to recognize differences with others, and to imagine new paths for shared journeys.',
    email: 'csjyseo@gmail.com',
    instagram: '',
    link: '',
  },
  {
    id: 21,
    whiteImageUrl: '/work/arrow_W/정현진=화살표_정현진_W.png',
    greenImageUrl: '/work/arrow_G/정현진=화살표_정현진_G.png',
    workTitle: 'Broken Heart',
    workTitle2: 'Broken Heart: The broken window theory',
    name: '정현진',
    englishName: 'Chong Hyeonjin',
    intro: '당신의 창문은 안전한가?',
    koreanExplanation:
      '당신의 유리창은 언제까지 안전할 수 있을까요. “건물의 깨진 유리창 하나를 방치하면 곧 그 건물의 모든 유리창이 깨진다.” 작은 무질서를 방치하면 큰 범죄로 이어진다는 ‘깨진 유리창의 법칙’을 들어보셨을 것입니다. 이는 단순히 물리적 환경에만 국한되지 않습니다. 사소한 거짓말부터 범국가적 폭력에 대한 침묵과 방관은 더 큰 악을 정당화하는 초석이 됩니다. 1982년 미국의 범죄학자 제임스 윌슨과 조지 켈링이 제시한 이 이론은 오늘날 전 세계 곳곳에서 끊임없이 증명되고 있습니다. 한 개인의 편의를 위한 작은 타협이 사회 전체의 도덕적 붕괴로 이어지는 과정을 우리는 역사 속에서, 그리고 현재 가자 지구에서 목격하고 있습니다. 가자 지구의 참상은 우리에게 묻습니다. 당신의 유리창은 언제까지 안전할 것이라고 단언할 수 있습니까?',
    englishExplanation: `Guarantee: your windows will remain safe forever."If a single broken window in a building is left unrepaired, soon all the windows in that building will be broken." You must have heard of the 'Broken Windows Theory' the idea that tolerating small acts of disorder leads to major crime. This principle extends far beyond the physical environment. From small lies to silence and indifference toward state sanctioned violence, these seemingly minor compromises become the foundation that justifies greater evil. This theory, proposed in 1982 by American criminologists James Wilson and George Kelling, continues to be proven across the world today. We witness this process how small personal compromises made for convenience lead to the moral collapse of entire societies both throughout history and in present day Gaza. The devastation in Gaza poses a question to you: Can you truly guarantee that your windows will remain safe forever?`,
    email: 'sorpdhktlsth1@icloud.com',
    instagram: '',
    link: '',
  },
  {
    id: 22,
    whiteImageUrl: '/work/arrow_W/정환이=화살표_정환이_W.png',
    greenImageUrl: '/work/arrow_G/정환이=화살표_정환이_G.png',
    workTitle: '靑連',
    workTitle2: '청연',
    name: '정환이',
    englishName: 'Jung Hwanyi',
    intro: '흩어진 순간을 기록해,개인의 청사진을 완성하는 靑連',
    koreanExplanation:
      '「靑連(청연)」은 디지털 시대에 정보는 넘쳐나지만 이를 수용하고 체계화하는 힘이 부족하다는 문제의식에서 출발했습니다. 이를 보완하기 위해 손으로 남기는 기록을 제안하며, 작은 기록들을 모아 ‘나’를 이해하고 미래를 설계할 수 있도록 합니다. 청연은 특히 청년들을 대상으로, 인덱스 기록박스를 비롯한 기록 제품을 통해 개인의 청사진이 완성되도록 돕는 브랜드입니다.',
    englishExplanation:
      '「靑連(Cheongyeon)」 was born from the awareness that while the digital age overflows with information, our ability to absorb and organize it often falls short. To address this, the brand proposes handwritten records small traces that help us understand ourselves and design our futures. Aimed especially at young people, Cheongyeon provides an Index Record Box and related tools that support the completion of each individual’s personal blueprint.',
    email: 'abcabc0103_@naver.com',
    instagram: '',
    link: 'https://www.behance.net/bc3f8b57',
  },
];
