export const arrows = [
  {
    id: 1,
    whiteImageUrl: '/work/1_W.png',
    greenImageUrl: '/work/1_G.png',
    name: '강유진',
  },
  {
    id: 2,
    whiteImageUrl: '/work/2_W.png',
    greenImageUrl: '/work/2_G.png',
    name: '강현정',
  },
  {
    id: 3,
    whiteImageUrl: '/work/3_W.png',
    greenImageUrl: '/work/3_G.png',
    name: '권민정',
  },
  {
    id: 4,
    whiteImageUrl: '/work/4_W.png',
    greenImageUrl: '/work/4_G.png',
    name: '김도영',
  },
  {
    id: 5,
    whiteImageUrl: '/work/5_W.png',
    greenImageUrl: '/work/5_G.png',
    name: '김민구',
  },
  {
    id: 6,
    whiteImageUrl: '/work/6_W.png',
    greenImageUrl: '/work/6_G.png',
    name: '김승화',
  },
  {
    id: 7,
    whiteImageUrl: '/work/7_W.png',
    greenImageUrl: '/work/7_G.png',
    name: '김은지',
  },
  {
    id: 8,
    whiteImageUrl: '/work/8_W.png',
    greenImageUrl: '/work/8_G.png',
    name: '김주훈',
  },
  {
    id: 9,
    whiteImageUrl: '/work/9_W.png',
    greenImageUrl: '/work/9_G.png',
    name: '박소연',
  },
  {
    id: 10,
    whiteImageUrl: '/work/10_W.png',
    greenImageUrl: '/work/10_G.png',
    name: '박수민',
  },
  {
    id: 11,
    whiteImageUrl: '/work/11_W.png',
    greenImageUrl: '/work/11_G.png',
    name: '박혜연',
  },
  {
    id: 12,
    whiteImageUrl: '/work/12_W.png',
    greenImageUrl: '/work/12_G.png',
    name: '박희건',
  },
  {
    id: 13,
    whiteImageUrl: '/work/13_W.png',
    greenImageUrl: '/work/13_G.png',
    name: '신유빈',
  },
  {
    id: 14,
    whiteImageUrl: '/work/14_W.png',
    greenImageUrl: '/work/14_G.png',
    name: '안수아',
  },
  {
    id: 15,
    whiteImageUrl: '/work/15_W.png',
    greenImageUrl: '/work/15_G.png',
    name: '오서현',
  },
  {
    id: 16,
    whiteImageUrl: '/work/16_W.png',
    greenImageUrl: '/work/16_G.png',
    name: '오지홍',
  },
  {
    id: 17,
    whiteImageUrl: '/work/17_W.png',
    greenImageUrl: '/work/17_G.png',
    name: '원민정',
  },
  {
    id: 18,
    whiteImageUrl: '/work/18_W.png',
    greenImageUrl: '/work/18_G.png',
    name: '이윤서',
  },
  {
    id: 19,
    whiteImageUrl: '/work/19_W.png',
    greenImageUrl: '/work/19_G.png',
    name: '이지혁',
  },
  {
    id: 20,
    whiteImageUrl: '/work/20_W.png',
    greenImageUrl: '/work/20_G.png',
    name: '전윤서',
  },
  {
    id: 21,
    whiteImageUrl: '/work/21_W.png',
    greenImageUrl: '/work/21_G.png',
    name: '정현진',
  },
  {
    id: 22,
    whiteImageUrl: '/work/22_W.png',
    greenImageUrl: '/work/22_G.png',
    name: '정환이',
  },
] as const;
