export const profile = [
  {
    id: 1,
    name: '강유진',
    profileUrl: '/profile/individual-profiles-all/강유진.png',
    profileDetailUrl: '/profile/individual-profiles-detail/강유진.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_강유진_G.png',
  },
  {
    id: 2,
    name: '강현정',
    profileUrl: '/profile/individual-profiles-all/강현정.png',
    profileDetailUrl: '/profile/individual-profiles-detail/강현정.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_강현정_G.png',
  },
  {
    id: 3,
    name: '권민정',
    profileUrl: '/profile/individual-profiles-all/권민정.png',
    profileDetailUrl: '/profile/individual-profiles-detail/권민정.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_권민정_G.png',
  },
  {
    id: 4,
    name: '김도영',
    profileUrl: '/profile/individual-profiles-all/김도영.png',
    profileDetailUrl: '/profile/individual-profiles-detail/김도영.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_김도영_G.png',
  },
  {
    id: 5,
    name: '김민구',
    profileUrl: '/profile/individual-profiles-all/김민구.png',
    profileDetailUrl: '/profile/individual-profiles-detail/김민구.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_김민구_G.png',
  },
  {
    id: 6,
    name: '김승화',
    profileUrl: '/profile/individual-profiles-all/김승화.png',
    profileDetailUrl: '/profile/individual-profiles-detail/김승화.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_김승화_G.png',
  },
  {
    id: 7,
    name: '김은지',
    profileUrl: '/profile/individual-profiles-all/김은지.png',
    profileDetailUrl: '/profile/individual-profiles-detail/김은지.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_김은지_G.png',
  },
  {
    id: 8,
    name: '김주훈',
    profileUrl: '/profile/individual-profiles-all/김주훈.png',
    profileDetailUrl: '/profile/individual-profiles-detail/김주훈.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_김주훈_G.png',
  },
  {
    id: 9,
    name: '박소연',
    profileUrl: '/profile/individual-profiles-all/박소연.png',
    profileDetailUrl: '/profile/individual-profiles-detail/박소연.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_박소연_G.png',
  },
  {
    id: 10,
    name: '박수민',
    profileUrl: '/profile/individual-profiles-all/박수민.png',
    profileDetailUrl: '/profile/individual-profiles-detail/박수민.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_박수민_G.png',
  },
  {
    id: 11,
    name: '박해연',
    profileUrl: '/profile/individual-profiles-all/박해연.png',
    profileDetailUrl: '/profile/individual-profiles-detail/박해연.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_박해연_G.png',
  },
  {
    id: 12,
    name: '박희건',
    profileUrl: '/profile/individual-profiles-all/박희건.png',
    profileDetailUrl: '/profile/individual-profiles-detail/박희건.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_박희건_G.png',
  },
  {
    id: 13,
    name: '신유빈',
    profileUrl: '/profile/individual-profiles-all/신유빈.png',
    profileDetailUrl: '/profile/individual-profiles-detail/신유빈.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_신유빈_G.png',
  },
  {
    id: 14,
    name: '안수아',
    profileUrl: '/profile/individual-profiles-all/안수아.png',
    profileDetailUrl: '/profile/individual-profiles-detail/안수아.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_안수아_G.png',
  },
  {
    id: 15,
    name: '오서현',
    profileUrl: '/profile/individual-profiles-all/오서현.png',
    profileDetailUrl: '/profile/individual-profiles-detail/오서현.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_오서현_G.png',
  },
  {
    id: 16,
    name: '오지홍',
    profileUrl: '/profile/individual-profiles-all/오지홍.png',
    profileDetailUrl: '/profile/individual-profiles-detail/오지홍.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_오지홍_G.png',
  },
  {
    id: 17,
    name: '원민정',
    profileUrl: '/profile/individual-profiles-all/원민정.png',
    profileDetailUrl: '/profile/individual-profiles-detail/원민정.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_원민정_G.png',
  },
  {
    id: 18,
    name: '이윤서',
    profileUrl: '/profile/individual-profiles-all/이윤서.png',
    profileDetailUrl: '/profile/individual-profiles-detail/이윤서.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_이윤서_G.png',
  },
  {
    id: 19,
    name: '이지혁',
    profileUrl: '/profile/individual-profiles-all/이지혁.png',
    profileDetailUrl: '/profile/individual-profiles-detail/이지혁.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_이지혁_G.png',
  },
  {
    id: 20,
    name: '전윤서',
    profileUrl: '/profile/individual-profiles-all/전윤서.png',
    profileDetailUrl: '/profile/individual-profiles-detail/전윤서.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_전윤서_G.png',
  },
  {
    id: 21,
    name: '정현진',
    profileUrl: '/profile/individual-profiles-all/정현진.png',
    profileDetailUrl: '/profile/individual-profiles-detail/정현진.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_정현진_G.png',
  },
  {
    id: 22,
    name: '정환이',
    profileUrl: '/profile/individual-profiles-all/정환이.png',
    profileDetailUrl: '/profile/individual-profiles-detail/정환이.png',
    arrowUrl: '/profile/arrows-profile-background/화살표_정환이_G.png',
  },
] as const;
